# Roadkill Data Preprocessing

This notebook demonstrates the geospatial preprocessing pipeline for roadkill incident data 
in Gangwon Province, Korea (2020–2022).  

The goal of preprocessing is to integrate multiple raw datasets (roadkill incidents, 
ecological corridors, wildlife damage ratios, and administrative boundaries) into a 
**unified grid-level feature dataset** that can be used for exploratory data analysis (EDA), 
statistical modeling, and spatial visualization.  

Specifically, this notebook:

1. Imports required Python libraries  
2. Loads administrative boundaries and constructs a spatial grid over Gangwon Province  
3. Loads and maps roadkill incident data (2020–2022) to the grid  
4. Aggregates incident counts at the grid level  
5. Loads ecological corridor data, maps to the grid, and computes corridor counts  
6. Calculates nearest ecological corridor distance for each grid cell  
7. Computes area-weighted wild boar and roe deer damage ratios by grid  
8. Flags Hongcheon County grids (홍천군) with a binary indicator  
9. Exports the processed datasets in CSV and GeoJSON formats for analysis and visualization

## Imports

In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import box, Point
from sklearn.neighbors import BallTree
import matplotlib.pyplot as plt
import folium
from folium.plugins import HeatMap
from collections import defaultdict
import os

## Define Data Paths

We specify the base data directory and set paths for administrative boundaries, roadkill incidents, wildlife corridors, and species-damage datasets to keep the workflow organized.

In [5]:
# Root directory for all datasets
data_path = '/Users/yeji_kim/Desktop/project/roadkill_analysis/data'
raw_path = os.path.join(data_path, 'raw')

# Administrative boundaries
boundary_path = os.path.join(raw_path, 'SouthKoreaApi')

# Roadkill incidents
roadkill_path = os.path.join(raw_path, 'roadkill')

# Wildlife corridors
wildlife_corridor_path = os.path.join(raw_path, 'wildlife_corridor')

# Species damage reports (roe deer, wild boar)
species_damage_path = os.path.join(raw_path, 'species_damage')
roe_deer_path = os.path.join(species_damage_path, 'roe_deer')
wild_boar_path = os.path.join(species_damage_path, 'wild_boar')

## 1. Load Administrative Boundaries

We load the shapefile of administrative boundaries for South Korea and filter **Gangwon Province** (강원특별자치도).  
All layers are projected to EPSG:4326 for consistency.

In [3]:
# Load shapefile of provincial boundaries
boundary_gdf = gpd.read_file(boundary_path, encoding='cp949').to_crs(epsg = 4326)

# Filter Gangwon Province
gangwon_boundary = boundary_gdf[boundary_gdf['CTP_KOR_NM'] == '강원특별자치도']

## 2. Create Grid Over Gangwon Province 

We construct a grid covering Gangwon Province using a bounding box.
Each grid cell is 0.05 * 0.05 degrees, and only cells that intersect with Gangwon are retained.

In [4]:
# Get bounding box
min_x, min_y, max_x, max_y = gangwon_boundary.total_bounds
grid_size = 0.05

# Generate grid cells across the bounding box
grid_cells, grid_ids, grid_id = [],[], 1

x = min_x
while x < max_x:
    y = min_y
    while y < max_y:
        grid_cells.append(box(x,y, x + grid_size, y + grid_size))
        grid_ids.append(f'grid_{grid_id}')
        grid_id += 1
        y += grid_size
    x += grid_size

# Convert to GeoDataFrame   
grid = gpd.GeoDataFrame({'grid_id': grid_ids, 'geometry': grid_cells}, crs = 'EPSG:4326')

# Keep only cells intersecting with Gangwon Providence
gangwon_grid = gpd.sjoin(grid, gangwon_boundary, how='inner', predicate='intersects').drop(columns='index_right')
gangwon_grid = gangwon_grid[['grid_id', 'geometry']]

## 3. Load Roadkill Incident Data

We load the roadkill incident data files for 2020–2022.  
The datasets include longitude and latitude for each incident, which will later be mapped to grid cells.

In [5]:
# Load yearly roadkill datasets into a dictionary
roadkill = {}
for file in os.listdir(roadkill_path):
    year = int(file[:4])
    df = pd.read_excel(os.path.join(roadkill_path, file))
    roadkill[year] = df
    
# Combine all years into a single DataFrame
roadkill_data = pd.concat(roadkill.values(), ignore_index = True)
roadkill_data = roadkill_data.rename(
    columns = {'GPS X': 'longitude', 'GPS Y':'latitude'}
    )

roadkill_data.head()

,일련번호,신고구분,신고내용,접수일자,접수시각,관할기관,longitude,latitude
0,4776,로드킬,부산 북구 덕천동 132-67 번지에서 로드킬이 발생하였습니다.,2021-12-31,21:12,부산 북구,129.021598,35.210053
1,4775,로드킬,경기 고양시 일산동구 중산동 1780 번지에서 로드킬이 발생하였습니다.,2021-12-31,19:08,경기 고양시 일산동구,126.790437,37.684049
2,4774,로드킬,서울 강서구 방화동 281-38 번지에서 로드킬이 발생하였습니다.,2021-12-31,18:46,서울 강서구,126.815437,37.572090
3,4773,로드킬,경기 이천시 설성면 장천리 232-2 번지에서 로드킬이 발생하였습니다.,2021-12-31,18:29,경기 이천시,127.525797,37.139656
4,4772,로드킬,인천 서구 마전동 1096 번지에서 로드킬이 발생하였습니다.,2021-12-31,18:22,인천 서구,126.675922,37.598946

## 4. Map Roadkill Incidents to Gangwon Grid

We convert the dataset to a GeoDataFrame (EPSG:4326), keep incidents within Gangwon Province, and map points to grid cells via a spatial join.

In [6]:
# To GeoDataFrame (x=longitude, y=latitude)
roadkill_gdf = gpd.GeoDataFrame(
    roadkill_data, geometry = gpd.points_from_xy(
        roadkill_data['longitude'], roadkill_data['latitude']),crs ='EPSG:4326'
    )


# Keep incidents within Gangwon Province
roadkill_gangwon = gpd.sjoin(
    roadkill_gdf, gangwon_boundary, how = 'inner', predicate = 'within').drop(columns = 'index_right')

In [7]:
# Add 1-per-incident flag for aggregation
roadkill_gangwon["roadkill_count"] = 1

# Assign incidents to grid cells (keep all grid cells)
roadkill_grid_gangwon = gpd.sjoin(
    roadkill_gangwon, gangwon_grid, how = 'right', predicate = 'within'
    )[['grid_id','longitude', 'latitude','roadkill_count']]
roadkill_grid_gangwon.tail()

        grid_id   longitude   latitude  roadkill_count
1413  grid_1414  129.301094  37.288755             1.0
1413  grid_1414  129.314704  37.286061             1.0
1442  grid_1443         NaN        NaN             NaN
1443  grid_1444         NaN        NaN             NaN
1444  grid_1445         NaN        NaN             NaN

## 5. Aggregate Roadkill Counts by Grid

We count the number of roadkill incidents per grid cell.  
Cells with no incidents are assigned a count of zero,  
resulting in a complete grid-level dataset.

In [8]:
# Count incidents per grid_id
roadkill_stats = (
    roadkill_grid_gangwon.groupby('grid_id')['roadkill_count'].sum().reset_index().astype({'roadkill_count':'int'})
    )
# Merge aggregated counts back with grid geometry
grid_features = gangwon_grid.merge(roadkill_stats, on = 'grid_id', how = 'left')
    
grid_features.head()

   grid_id                                           geometry  roadkill_count
0  grid_25  POLYGON ((127.14504 38.22783, 127.14504 38.277...               0
1  grid_26  POLYGON ((127.14504 38.27783, 127.14504 38.327...               0
2  grid_55  POLYGON ((127.19504 38.12783, 127.19504 38.177...               0
3  grid_56  POLYGON ((127.19504 38.17783, 127.19504 38.227...               0
4  grid_57  POLYGON ((127.19504 38.22783, 127.19504 38.277...               0

In [9]:
roadkill_stats

       grid_id  roadkill_count
0    grid_1000               0
1    grid_1001               0
2    grid_1002               0
3    grid_1003               0
4    grid_1004               0
..         ...             ...
779   grid_995               0
780   grid_996               0
781   grid_997               0
782   grid_998               0
783   grid_999               3

[784 rows x 2 columns]

## 6. Load Ecological Corridor Data
We load the ecological corridor dataset from Excel.  
Latitude and longitude were obtained by geocoding the original addresses.  
The dataset is prepared for conversion into a GeoDataFrame (EPSG:4326).

In [10]:
# Load ecological corridor dataset (Excel)
wildlife_corridor_data = pd.read_excel(os.path.join(wildlife_corridor_path, os.listdir(wildlife_corridor_path)[0]))

# Standardize column names to English
wildlife_corridor_data = wildlife_corridor_data.rename(
    columns = {'위도': 'latitude', '경도':'longitude'}
    )

# Keep only coordinates
wildlife_corridor_data = wildlife_corridor_data[['latitude','longitude']]

## 7. Map Ecological Corridors to Gangwon Grid
We convert corridor points to a GeoDataFrame (EPSG:4326), keep only those within Gangwon Province, and assign points to grid cells.

In [11]:
# To GeoDataFrame (x=longitude, y=latitude)
wildlife_corridor_gdf = gpd.GeoDataFrame(    
    wildlife_corridor_data, 
    geometry = gpd.points_from_xy(
        wildlife_corridor_data['longitude'],wildlife_corridor_data['latitude']
    ),
    crs = 'EPSG:4326'
    
)

# Keep corridors within Gangwon Province
wildlife_corridor_gangwon = gpd.sjoin(
    wildlife_corridor_gdf, gangwon_boundary, how = 'inner', predicate = 'within').drop(columns = 'index_right')

In [12]:
wildlife_corridor_gangwon

,latitude,longitude,geometry,CTPRVN_CD,CTP_ENG_NM,CTP_KOR_NM
23,37.493356,128.148598,POINT (128.1486 37.49336),51,Gangwon-do,강원특별자치도
24,38.022205,128.226368,POINT (128.22637 38.02221),51,Gangwon-do,강원특별자치도
25,37.832076,128.227259,POINT (128.22726 37.83208),51,Gangwon-do,강원특별자치도
26,38.118039,128.349715,POINT (128.34972 38.11804),51,Gangwon-do,강원특별자치도
27,37.920368,128.501581,POINT (128.50158 37.92037),51,Gangwon-do,강원특별자치도
...,...,...,...,...,...,...
579,37.209188,129.337363,POINT (129.33736 37.20919),51,Gangwon-do,강원특별자치도
590,37.500174,129.091262,POINT (129.09126 37.50017),51,Gangwon-do,강원특별자치도
601,38.559031,128.401541,POINT (128.40154 38.55903),51,Gangwon-do,강원특별자치도
612,38.216200,128.505714,POINT (128.50571 38.2162),51,Gangwon-do,강원특별자치도
613,37.687224,128.916707,POINT (128.91671 37.68722),51,Gangwon-do,강원특별자치도

In [13]:
# Add 1-per-corridor flag for aggregation
wildlife_corridor_gangwon['corridor_count'] = 1

# Assign corridors to grid cells (keep all grid cells)
wildlife_corridor_grid_gangwon = gpd.sjoin(
    wildlife_corridor_gangwon, gangwon_grid, how = 'right', predicate = 'within'
    )[['grid_id','longitude', 'latitude','corridor_count']]

In [14]:
wildlife_corridor_grid_gangwon

        grid_id  longitude  latitude  corridor_count
24      grid_25        NaN       NaN             NaN
25      grid_26        NaN       NaN             NaN
54      grid_55        NaN       NaN             NaN
55      grid_56        NaN       NaN             NaN
56      grid_57        NaN       NaN             NaN
...         ...        ...       ...             ...
1412  grid_1413        NaN       NaN             NaN
1413  grid_1414        NaN       NaN             NaN
1442  grid_1443        NaN       NaN             NaN
1443  grid_1444        NaN       NaN             NaN
1444  grid_1445        NaN       NaN             NaN

[806 rows x 4 columns]

## 8. Aggregate Ecological Corridor Counts by Grid

We count the number of ecological corridors per grid cell.
Cells with no corridors are assigned zero, resulting in a complete grid-level dataset.

In [15]:
# Count incidents per grid_id
corridor_stats = (
    wildlife_corridor_grid_gangwon.groupby('grid_id')['corridor_count'].sum().reset_index()
)
# Merge corridor_count to the existing grid_features
grid_features = grid_features.merge(corridor_stats, on = 'grid_id', how = 'left')
grid_features['corridor_count'] = grid_features['corridor_count'].fillna(0).astype(int)

grid_features.head()

,grid_id,geometry,roadkill_count,corridor_count
0,grid_25,"POLYGON ((127.14504 38.22783, 127.14504 38.277...",0,0
1,grid_26,"POLYGON ((127.14504 38.27783, 127.14504 38.327...",0,0
2,grid_55,"POLYGON ((127.19504 38.12783, 127.19504 38.177...",0,0
3,grid_56,"POLYGON ((127.19504 38.17783, 127.19504 38.227...",0,0
4,grid_57,"POLYGON ((127.19504 38.22783, 127.19504 38.277...",0,0

In [16]:
corridor_stats

       grid_id  corridor_count
0    grid_1000             0.0
1    grid_1001             0.0
2    grid_1002             0.0
3    grid_1003             0.0
4    grid_1004             0.0
..         ...             ...
779   grid_995             0.0
780   grid_996             0.0
781   grid_997             0.0
782   grid_998             0.0
783   grid_999             0.0

[784 rows x 2 columns]

## 9. Nearest Corridor Distance (per Grid)

For each roadkill incident, we calculate the distance to the nearest ecological corridor  
using a Haversine BallTree.  
At the grid level, we assign the shortest distance among incidents,  
and grids with no incidents are set to 0.

In [17]:
# Earth radius in meters
earth_radius_meter = 6_371_000

# Coordinates of incidents and corridors (Gangwon only)
rk_latlon  = roadkill_gangwon[['latitude', 'longitude']].to_numpy()
eco_latlon = wildlife_corridor_gangwon[['latitude', 'longitude']].to_numpy()

# Convert to radians for haversine metric
rk_radians  = np.radians(rk_latlon)
eco_radians = np.radians(eco_latlon)

In [18]:
wildlife_corridor_gangwon

,latitude,longitude,geometry,CTPRVN_CD,CTP_ENG_NM,CTP_KOR_NM,corridor_count
23,37.493356,128.148598,POINT (128.1486 37.49336),51,Gangwon-do,강원특별자치도,1
24,38.022205,128.226368,POINT (128.22637 38.02221),51,Gangwon-do,강원특별자치도,1
25,37.832076,128.227259,POINT (128.22726 37.83208),51,Gangwon-do,강원특별자치도,1
26,38.118039,128.349715,POINT (128.34972 38.11804),51,Gangwon-do,강원특별자치도,1
27,37.920368,128.501581,POINT (128.50158 37.92037),51,Gangwon-do,강원특별자치도,1
...,...,...,...,...,...,...,...
579,37.209188,129.337363,POINT (129.33736 37.20919),51,Gangwon-do,강원특별자치도,1
590,37.500174,129.091262,POINT (129.09126 37.50017),51,Gangwon-do,강원특별자치도,1
601,38.559031,128.401541,POINT (128.40154 38.55903),51,Gangwon-do,강원특별자치도,1
612,38.216200,128.505714,POINT (128.50571 38.2162),51,Gangwon-do,강원특별자치도,1
613,37.687224,128.916707,POINT (128.91671 37.68722),51,Gangwon-do,강원특별자치도,1

In [19]:
# Build BallTree on corridor points
tree = BallTree(eco_radians, metric = 'haversine')

# Query nearest corridor for each roadkill point
dist_rad, idx = tree.query(rk_radians, k = 1)

# Convert distance from radians → meters
dist_m = (dist_rad.flatten() * earth_radius_meter).astype(float)

In [20]:
# Incident-level nearest corridor info
rk_nearest = roadkill_gangwon[['latitude', 'longitude']].copy()
rk_nearest['nearest_corridor_idx'] = idx.flatten()
rk_nearest['dist_to_corridor']   = dist_m

# Attach nearest corridor coordinates (lat/lon)
rk_nearest['nearest_corridor_lat'] = eco_latlon[rk_nearest['nearest_corridor_idx'], 0]
rk_nearest['nearest_corridor_lon'] = eco_latlon[rk_nearest['nearest_corridor_idx'], 1]

# Add grid_id from roadkill-grid join
rk_nearest['grid_id'] = roadkill_gangwon.sjoin(
    gangwon_grid, how = 'left', predicate = 'within'
    )['grid_id']

In [21]:
# Grid-level minimum distance
min_distance_grid = (
    rk_nearest.groupby('grid_id')['dist_to_corridor'].min().reset_index().rename(columns = {'dist_to_corridor': 'min_dist_to_corridor'})
    )

# Merge into grid_features
grid_features = grid_features.merge(min_distance_grid, on='grid_id', how='left')

# Fill NaN with 0 for grids without incidents
grid_features['min_dist_to_corridor'] = grid_features['min_dist_to_corridor'].fillna(0).astype(float)

grid_features.head()

,grid_id,geometry,roadkill_count,corridor_count,min_dist_to_corridor
0,grid_25,"POLYGON ((127.14504 38.22783, 127.14504 38.277...",0,0,0.0
1,grid_26,"POLYGON ((127.14504 38.27783, 127.14504 38.327...",0,0,0.0
2,grid_55,"POLYGON ((127.19504 38.12783, 127.19504 38.177...",0,0,0.0
3,grid_56,"POLYGON ((127.19504 38.17783, 127.19504 38.227...",0,0,0.0
4,grid_57,"POLYGON ((127.19504 38.22783, 127.19504 38.277...",0,0,0.0

## 10. Wild Boar Damage Ratio by Grid
We calculate the area-weighted average wild boar damage ratio per grid cell.
Each polygon is reprojected to a metric CRS, intersected with the grid, and weighted by overlap area.

In [22]:
# Load wild boar polygons (Gangwon only)
wild_boar_gdf = gpd.read_file(wild_boar_path, encoding='cp949').to_crs(epsg = 4326)
wild_boar_gangwon = wild_boar_gdf[wild_boar_gdf['ADM_NM'].str.contains('강원도')]

# Reproject to metric CRS for area calculation
grid_metric = gangwon_grid.to_crs(epsg = 5179)
boar_metric = wild_boar_gangwon.to_crs(epsg = 5179)

# Grid × polygon intersection
boar_inter = gpd.overlay(grid_metric, boar_metric, how='intersection')
boar_inter['inter_area'] = boar_inter.geometry.area

# Area-weighted average ratio per grid
boar_ratio_by_grid = (
    boar_inter
    .assign(weight=lambda d: d['inter_area'])
    .groupby('grid_id')
    .apply(lambda d: np.average(d['멧돼지'], weights=d['weight']))
    .rename('wild_boar_grid')
    .reset_index()
    )

# Merge into grid features
grid_features = grid_features.merge(boar_ratio_by_grid, on="grid_id", how="left")

## 11. Roe Deer Damage Ratio by Grid

The same procedure is applied to roe deer polygons to compute an area-weighted average ratio per grid.

In [23]:
# Load roe deer polygons (Gangwon only)
roe_deer_gdf = gpd.read_file(roe_deer_path, encoding='cp949').to_crs(epsg = 4326)
roe_deer_gangwon= roe_deer_gdf[roe_deer_gdf['ADM_NM'].str.contains('강원도')]

# Reproject to metric CRS for area calculation
roe_metric = roe_deer_gangwon.to_crs(epsg = 5179)

# Grid × polygon intersection
roe_inter = gpd.overlay(grid_metric, roe_metric, how="intersection")
roe_inter["inter_area"] = roe_inter.geometry.area

# Area-weighted average ratio per grid
roe_ratio_by_grid = (
    roe_inter
    .assign(weight=lambda d: d['inter_area'])
    .groupby('grid_id')
    .apply(lambda d: np.average(d['고라니'], weights=d['weight']))
    .rename('roe_deer_grid')
    .reset_index()
)

# Merge into grid features
grid_features = grid_features.merge(roe_ratio_by_grid, on="grid_id", how="left")

In [24]:
grid_features

,grid_id,geometry,roadkill_count,corridor_count,min_dist_to_corridor,wild_boar_grid,roe_deer_grid
0,grid_25,"POLYGON ((127.14504 38.22783, 127.14504 38.277...",0,0,0.000000,0.401211,0.000000
1,grid_26,"POLYGON ((127.14504 38.27783, 127.14504 38.327...",0,0,0.000000,0.401211,0.000000
2,grid_55,"POLYGON ((127.19504 38.12783, 127.19504 38.177...",0,0,0.000000,0.401211,0.000000
3,grid_56,"POLYGON ((127.19504 38.17783, 127.19504 38.227...",0,0,0.000000,0.401211,0.000000
4,grid_57,"POLYGON ((127.19504 38.22783, 127.19504 38.277...",0,0,0.000000,0.401211,0.000000
...,...,...,...,...,...,...,...
779,grid_1413,"POLYGON ((129.34504 37.22783, 129.34504 37.277...",0,0,0.000000,0.000000,0.262059
780,grid_1414,"POLYGON ((129.34504 37.27783, 129.34504 37.327...",2,0,8780.044607,0.000000,0.262059
781,grid_1443,"POLYGON ((129.39504 37.12783, 129.39504 37.177...",0,0,0.000000,0.000000,0.262059
782,grid_1444,"POLYGON ((129.39504 37.17783, 129.39504 37.227...",0,0,0.000000,0.000000,0.262059
783,grid_1445,"POLYGON ((129.39504 37.22783, 129.39504 37.277...",0,0,0.000000,0.000000,0.262059

## 12. Flag Hongcheon Grids

We identify whether each grid cell belongs to Hongcheon County (홍천군).
This is done by filtering the administrative polygons to Hongcheon,
performing a spatial join with the grid,
and assigning a binary indicator (is_hongcheon) to the grid-level dataset.

In [25]:
# Extract Hongcheon polygon from the admin boundaries
hongcheon_admin = (
    wild_boar_gangwon
    [wild_boar_gangwon['ADM_NM'].str.contains('홍천')]
    [['ADM_NM', 'geometry']]
    .rename(columns={'ADM_NM': 'admin_name'})
)

# Spatial join: grid × Hongcheon polygon
hongcheon_grid = (
    gpd.sjoin(gangwon_grid, hongcheon_admin, how='inner',predicate='intersects').drop(columns = 'index_right')
) 

# Add binary flag to grid_features
grid_features['is_hongcheon'] = grid_features['grid_id'].isin(hongcheon_grid['grid_id']).astype(int)

## 13. Export Processed Datasets

We export the processed datasets in both **CSV** (for analysis) and **GeoJSON** (for visualization) formats.  
This ensures that the data are ready for machine learning pipelines while also being directly usable in mapping tools such as **Folium** and **Tableau**.

- **Grid-level features**
  - `grid_features.csv`: tabular dataset with counts, ratios, and administrative units
  - `grid_features.geojson`: spatial dataset for visualization

- **Roadkill incidents**
  - `roadkill_points.csv`: latitude/longitude with incident counts
  - `roadkill_points.geojson`: geospatial points for mapping

- **Ecological corridors**
  - `wildlife_corridor_points.csv`: latitude/longitude with corridor counts
  - `wildlife_corridor_points.geojson`: geospatial points for mapping

In [26]:
processed_path =  os.path.join(data_path, 'processed')

# Ensure grid_features is in EPSG:4326
grid_features = grid_features.to_crs(epsg=4326)

# 1. Grid-level features
grid_features.to_csv(
    os.path.join(processed_path, 'grid_features.csv'),
    index=False
)
grid_features.to_file(
    os.path.join(processed_path, 'grid_features.geojson'),
    driver='GeoJSON'
)

# 2. Roadkill points
roadkill_gangwon[['latitude', 'longitude', 'roadkill_count']].to_csv(
    os.path.join(processed_path, 'roadkill_points.csv'),
    index=False
)
roadkill_gangwon.to_file(
    os.path.join(processed_path, 'roadkill_points.geojson'),
    driver='GeoJSON'
)

# 3. Ecological corridor points
wildlife_corridor_gangwon[['latitude', 'longitude', 'corridor_count']].to_csv(
    os.path.join(processed_path, 'wildlife_corridor_points.csv'),
    index=False
)
wildlife_corridor_gangwon.to_file(
    os.path.join(processed_path, 'wildlife_corridor_points.geojson'),
    driver='GeoJSON'
)

In [ ]:
gdf = gpd.read_file(boundary_path + '/ctp_rvn.shp')
gdf.to_file(os.path.join(boundary_path, 'ctp_rvn.geojson'), driver='GeoJSON')